In [1]:
import numpy as np
import torch 


In [2]:
torch.cuda.is_available()

False

In [3]:
some_data = [[1,2],[3,4]]

In [4]:
type(some_data)

list

In [5]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [7]:
some_data = torch.tensor(some_data)

In [8]:
type(some_data)

torch.Tensor

In [9]:
some_data.dtype

torch.int64

In [10]:
numpy_array = np.random.rand(3, 4)
numpy_array

array([[0.27922602, 0.94812552, 0.89172023, 0.56907283],
       [0.87957048, 0.39235839, 0.23733663, 0.77086566],
       [0.41139735, 0.52801225, 0.29121962, 0.46410543]])

In [11]:
torch.from_numpy(numpy_array)

tensor([[0.2792, 0.9481, 0.8917, 0.5691],
        [0.8796, 0.3924, 0.2373, 0.7709],
        [0.4114, 0.5280, 0.2912, 0.4641]], dtype=torch.float64)

In [12]:
torch.tensor(numpy_array)

tensor([[0.2792, 0.9481, 0.8917, 0.5691],
        [0.8796, 0.3924, 0.2373, 0.7709],
        [0.4114, 0.5280, 0.2912, 0.4641]], dtype=torch.float64)

In [13]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
my_tensor = torch.rand(3, 4)

In [17]:
my_tensor.dtype

torch.float32

In [18]:
my_tensor.device

device(type='cpu')

In [ ]:
# my_tensor = my_tensor.to('cuda:0')

In [20]:
my_tensor[:, 1:3]

tensor([[0.8283, 0.4445],
        [0.6976, 0.7031],
        [0.5965, 0.1906]])

In [21]:
my_tensor.mul(my_tensor)

tensor([[0.0143, 0.6862, 0.1975, 0.9597],
        [0.0378, 0.4866, 0.4943, 0.0085],
        [0.1821, 0.3558, 0.0363, 0.0010]])

In [22]:
my_tensor * my_tensor

tensor([[0.0143, 0.6862, 0.1975, 0.9597],
        [0.0378, 0.4866, 0.4943, 0.0085],
        [0.1821, 0.3558, 0.0363, 0.0010]])

In [23]:
my_tensor.matmul(my_tensor.T)

tensor([[1.8577, 1.0037, 0.6604],
        [1.0037, 1.0272, 0.6359],
        [0.6604, 0.6359, 0.5751]])

In [24]:
torch.matmul(my_tensor, my_tensor.T)

tensor([[1.8577, 1.0037, 0.6604],
        [1.0037, 1.0272, 0.6359],
        [0.6604, 0.6359, 0.5751]])

In [25]:
my_tensor @ my_tensor.T

tensor([[1.8577, 1.0037, 0.6604],
        [1.0037, 1.0272, 0.6359],
        [0.6604, 0.6359, 0.5751]])

In [27]:
my_tensor.sum()

tensor(5.3040)

In [30]:
my_tensor

tensor([[0.1194, 0.8283, 0.4445, 0.9797],
        [0.1944, 0.6976, 0.7031, 0.0920],
        [0.4267, 0.5965, 0.1906, 0.0313]])

In [28]:
my_tensor.sum(axis=0)

tensor([0.7405, 2.1224, 1.3381, 1.1030])

In [29]:
my_tensor.sum(axis=1)

tensor([2.3719, 1.6871, 1.2450])

In [31]:
my_tensor.shape

torch.Size([3, 4])

In [32]:
my_tensor.size()

torch.Size([3, 4])

In [33]:
torch.rand(10, 3, 128, 128).size()

torch.Size([10, 3, 128, 128])

In [34]:
my_tensor

tensor([[0.1194, 0.8283, 0.4445, 0.9797],
        [0.1944, 0.6976, 0.7031, 0.0920],
        [0.4267, 0.5965, 0.1906, 0.0313]])

In [35]:
my_tensor.clip(0.2, 0.8)

tensor([[0.2000, 0.8000, 0.4445, 0.8000],
        [0.2000, 0.6976, 0.7031, 0.2000],
        [0.4267, 0.5965, 0.2000, 0.2000]])