In [1]:
import torch

In [4]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [5]:
y = a**3 - b**2

In [6]:
y

tensor([89.], grad_fn=<SubBackward0>)

In [ ]:
# dy/da = 3a^2 = 3*5^2 = 75
# dy/db = -2b = -2*6 = -12

In [7]:
print(a.grad)

None


In [8]:
y.backward()

In [9]:
a.grad

tensor([75.])

In [10]:
b.grad

tensor([-12.])

In [27]:
W = torch.randn(10, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

In [28]:
x = torch.rand(1, 10)

In [29]:
output = torch.matmul(x, W) + b

In [30]:
loss = 1 - output

In [31]:
loss

tensor([[-1.6358]], grad_fn=<RsubBackward1>)

In [32]:
loss.backward()

In [33]:
W.grad

tensor([[-0.0521],
        [-0.3748],
        [-0.9344],
        [-0.4700],
        [-0.5283],
        [-0.0013],
        [-0.7123],
        [-0.5692],
        [-0.9789],
        [-0.8756]])

In [34]:
with torch.no_grad():
    W = W - 0.001 * W.grad.data

In [35]:
W

tensor([[ 0.8611],
        [-0.8011],
        [ 0.5418],
        [ 1.3102],
        [ 0.5435],
        [-2.3068],
        [ 1.2621],
        [ 0.9524],
        [-1.1829],
        [ 0.2739]])